In [1]:
import numpy as np

In [38]:
a = np.ones((5,5))
a[1:4, 1:4] = [0]
a[2, 2:3] = [9]
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# Copying array with care

In [48]:
a = np.array([1,2,3])

# now i want to copy a to b

b = a
b

# now i want to change the 1st element in b 

b[0] = 12
print(b)

# the problem is it's also change the element in a
print(a)

# for to prevent that we use .copy() function
a = ([1,2,3,4,5])
print(a)

b = a.copy()
print(b)

b[0] = 12
print(a)
print(b)

[12  2  3]
[12  2  3]
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
[12, 2, 3, 4, 5]


# Mathematics

In [50]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [52]:
a + 2

array([3, 4, 5, 6])

In [53]:
a -2

array([-1,  0,  1,  2])

In [54]:
a * 2

array([2, 4, 6, 8])

In [56]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [57]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [58]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [65]:
# Getting the sin, cos, tan 
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128]


# Linear Algebra

In [73]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 4)
print(b)

# Default matrix multiplcation function
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[4 4]
 [4 4]
 [4 4]]


array([[12., 12.],
       [12., 12.]])