# if below command doesn't work you need to install numpy.
# type in cmd 'pip install numpy'

In [1]:
import numpy as np

# The Basic

In [2]:
a = np.array([1, 3 , 2, 5, 4], dtype = 'int16')
print(a)

[1 3 2 5 4]


In [3]:
b = np.array([[1.0, 2.0 ,3.0], [4.0, 5.0, 6]])
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


In [4]:
# get dimension

print(a.ndim)
print(b.ndim)

1
2


In [5]:
# get shape

print(a.shape)
print(b.shape)

(5,)
(2, 3)


In [6]:
# Get type
print(a.dtype)
print(b.dtype)

int16
float64


In [7]:
# Get Memory Size (bytes)

print(a.itemsize)
print(b.itemsize)

2
8


In [8]:
# get total size or total no of element in array

print(a.size * a.itemsize)
# or
a.nbytes

10


10

# Accessing/Changing Specific elements row, column etc

In [9]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [10]:
# Get Specific Element from an array [row, column]

a[1, 5]

13

In [11]:
#get the specific row

a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [12]:
#get the specific column

a[:, 2]

array([ 3, 10])

In [13]:
# Getting the selected elements from an array [startindex, endindex:stepsize]

print(a[1, 1 : 6 : 2])
print(a[1, 1 : -1 : 2])

[ 9 11 13]
[ 9 11 13]


In [14]:
#changing the value of specific element

a[1,3] = 17

print(a)
print()

# changing the specific row
# Changing whole row by 1
a[0, :] = 1
print(a)
print()

# changing the specific Column
# Changing whole column by 45

a[:, 3] = 45
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 17 12 13 14]]

[[ 1  1  1  1  1  1  1]
 [ 8  9 10 17 12 13 14]]

[[ 1  1  1 45  1  1  1]
 [ 8  9 10 45 12 13 14]]


# 3D Example

In [15]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [16]:
# get specific element (work inside out)

b[0,1,1]

4

In [17]:
# Replace
b[: , 1 , :] = [[5,5],[6,6]]
print(b)

[[[1 2]
  [5 5]]

 [[5 6]
  [6 6]]]


# Initializing differenet types of array

In [18]:
# All 0s matrix

np.zeros((2,3,4,5)) # four dimensional array of 0s

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [19]:
# ALL 1s matrix

np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
# Any other number 
# Takes two parameter (shape(2,3), Value(any nuumber you want))

np.full((2,5), 45)

array([[45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45]])

In [21]:
# any other number (full_like)

print(np.full_like(a, 3))
# or 
print(np.full(a.shape, 5))

[[3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3]]
[[5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5]]


In [22]:
# Random decimal number

print(np.random.rand(3, 5))
print()
# if you want specific array shape
np.random.random_sample(a.shape)


[[0.89780263 0.10128535 0.32673691 0.28961404 0.61578786]
 [0.45484104 0.44630674 0.07590629 0.90725823 0.16251457]
 [0.06950264 0.1046278  0.80059793 0.3470819  0.31970265]]



array([[0.40741553, 0.39923557, 0.75359432, 0.33194994, 0.67643546,
        0.67187668, 0.92750095],
       [0.07463072, 0.06924789, 0.79200034, 0.22637165, 0.95837902,
        0.23042361, 0.39987631]])

In [23]:
# random integer number (starting no, size=(2,3))

np.random.randint(-3,45, size = (3,5))

array([[28, 11, 21, 23, 16],
       [38,  2, 25, 32, 32],
       [18, 40,  2, 10, 40]])

In [24]:
# The identity Matrix

np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [25]:
# reapeat an array

arr = np.array([[1,2,3]])

r1 = np.repeat(arr, 4, axis = 0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


# Exercise

In [26]:
# Build an array like this while using what we've learned
# [[1. 1. 1. 1. 1.]
#  [1. 0. 0. 0. 1.]
#  [1. 0. 9. 0. 1.]
#  [1. 0. 0. 0. 1.]
#  [1. 1. 1. 1. 1.]]

# Copying array with care

In [27]:
a = np.array([1,2,3])
a
# now i want to copy a to b

b = a
b

# now i want to change the 1st element in b 

b[0] = 12
print(b)

# the problem is it's also change the element in a
print(a)

# for to prevent that we use .copy() function

a = ([1,2,3,4,5])
print(a)

b = a.copy()
print(b)

b[0] = 12
print(a)
print(b)

[12  2  3]
[12  2  3]
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
[12, 2, 3, 4, 5]


# Mathematics

In [28]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [29]:
a + 2
a

array([1, 2, 3, 4])

In [30]:
a - 2
a

array([1, 2, 3, 4])

In [31]:
a * 2
a

array([1, 2, 3, 4])

In [32]:
a / 2
a

array([1, 2, 3, 4])

In [33]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [34]:
# Getting the sin, cos, tan 
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128]


# Linear Algebra

In [35]:
a = np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [36]:
b = np.full((3,2), 4)
print(b)

[[4 4]
 [4 4]
 [4 4]]


In [37]:
# Default matrix multiplcation function
np.matmul(a,b)

array([[12., 12.],
       [12., 12.]])

In [38]:
# Find the determinater
c = np.identity(3)
c
# Linear Algerbra. Determinater
np.linalg.det(c)

1.0

# Statistics

In [40]:
stat = np.array([[1,2,3],[4,5,6]])
stat

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
#find the minimum value in array

print(np.min(stat))

#find the minimim value in each row
print(np.min(stat, axis=1))

#find the minimum Values in row, cloumn

print(np.min(stat, axis = 0))

1
[1 4]
[1 2 3]


In [49]:
#find the maximum value in array

print(np.max(stat))

#find the maxmium value in each row
print(np.max(stat, axis=1))

#find the maximum Values in Row, Column

print(np.max(stat, axis = 0))

6
[3 6]
[4 5 6]


In [52]:
print(np.sum(stat))

#find the minimim value in each row
print(np.sum(stat, axis=1))

#find the minimum Values in row, cloumn

print(np.sum(stat, axis = 0))

21
[ 6 15]
[5 7 9]


# Rearranging Arrays

In [57]:
before = np.array([[1,2,3,4,],[8,9,10,11,]])
print(before)

#Reshaping the array ou can reshape to any shape as long as it's has the same values
after = before.reshape((4,2))
print(after)

after = before.reshape((1,8))
print(after)

after = before.reshape((8,1))
print(after)

after = before.reshape((2,2,2))
print(after)
after = before.reshape((4,3))
print(after)

[[ 1  2  3  4]
 [ 8  9 10 11]]
[[ 1  2]
 [ 3  4]
 [ 8  9]
 [10 11]]
[[ 1  2  3  4  8  9 10 11]]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 8]
 [ 9]
 [10]
 [11]]
[[[ 1  2]
  [ 3  4]]

 [[ 8  9]
  [10 11]]]


ValueError: cannot reshape array of size 8 into shape (4,3)

In [62]:
# Vertically Stacking vector
v1 = np.array([1,2,3,4])
v2 = np. array([5,6,7,8])

vstack = np.vstack((v1,v2))
vstack

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [63]:
#horizontally Stacking vector

h1 = np.ones((2,4))
h2 = np.zeros((2,2))

hstack = np.hstack((h1,h2))
hstack

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# Miscellaneous

Load data from file

In [76]:
filedata = np.genfromtxt('data.txt', delimiter=',')
print(filedata.dtype)
print(filedata)

# changing the type of data
filedata = filedata.astype('int32')
print(filedata.dtype)
print(filedata)

float64
[[  1.  13.  21.  11. 196.  75.   4.   3.  34.   6.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 766.  75.   4.  55.   6.   4.   3.   4.   5.   6.
    7.   0.  11.  12.]
 [  1.  22.  33.  11. 999.  11.   2.   1.  78.   0.   1.   2.   9.   8.
    7.   1.  76.  88.]]
int32
[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


# Boolean Masking And Advanced Indexing

In [77]:
filedata > 23

array([[False, False, False, False,  True,  True, False, False,  True,
        False, False, False, False, False, False, False, False, False],
       [False,  True, False,  True,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False,  True, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [78]:
filedata < 50

array([[ True,  True,  True,  True, False, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [85]:
#Getting values greater than or less than or less than and equal or greater than and equal
print(filedata[filedata < 50])
print(filedata[filedata > 50])

[ 1 13 21 11  4  3 34  6  7  8  0  1  2  3  4  5  3 42 12 33  4  6  4  3
  4  5  6  7  0 11 12  1 22 33 11 11  2  1  0  1  2  9  8  7  1]
[196  75 766  75  55 999  78  76  88]


In [86]:
#Indexing the list in NumPy

a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,3,5,8]]

array([2, 4, 6, 9])

In [92]:
# Data greater than 30 but less than 100
print((((filedata > 30) & (filedata < 100))))

# Data not greater than 30 but less than 100
# ~ not equall sign
print((~((filedata > 30) & (filedata < 100))))

[[False False False False False  True False False  True False False False
  False False False False False False]
 [False  True False  True False  True False  True False False False False
  False False False False False False]
 [False False  True False False False False False  True False False False
  False False False False  True  True]]
[[ True  True  True  True  True False  True  True False  True  True  True
   True  True  True  True  True  True]
 [ True False  True False  True False  True False  True  True  True  True
   True  True  True  True  True  True]
 [ True  True False  True  True  True  True  True False  True  True  True
   True  True  True  True False False]]


In [113]:
a = np.random.randint(1,30, (5,6))
print(a)
print(a[[1,2,3,4],[1,2,3,4]])
print(a[2:4, 0:2])
print(a[[0,2,4], 3:])

[[ 8 22 12  6 15 25]
 [12 21 28 12 15 22]
 [26  5 14  6  6 21]
 [25  4  2  9 15  6]
 [22 16  5 22 17  1]]
[21 14  9 17]
[[26  5]
 [25  4]]
[[ 6 15 25]
 [ 6  6 21]
 [22 17  1]]
